### ISSUE TITLE
Translate to Russian Language 🇷🇺

### ISSUE THREAD

**Issue by guland2000** [foodcoopshop/foodcoopshop#975] opened 2023-11-09 18:23 UTC
Hi!
Want to translate in Russian Language 🇷🇺 , please let me do this,
Thanks!

todos
* [x] Open Sans with Cyrillic
* [x] Change font in PDFs (???? are shown)
* [x] PDF font: clean up code (use freesans for all locales, composer-post-install.sh)
* [x] Changelog PR updaten, Docs updaten, add link demo-ru.foodcoopshop.com

**Comment by mrothauer** [comment] 2023-11-09 19:46
Hi @guland2000,

no problem, just follow the translation guide:
https://foodcoopshop.github.io/en/translation-guide.html

I prepared a new branch (russian-translation) that contains a copy of the english translation files.

Example file to be edited:
https://github.com/foodcoopshop/foodcoopshop/blob/russian-translation/resources/locales/ru_RU/default.po

**Comment by guland2000** [comment] 2023-11-10 19:05
OK, but were to get this;
4. Translate InitDataSeed
[Configuration sql file](https://github.com/foodcoopshop/foodcoopshop/tree/develop/config/Seeds/locale/en_US/InitDataSeed.php)

**Comment by mrothauer** [comment] 2023-11-21 11:58
@guland2000 any questions?

**Comment by guland2000** [comment] 2023-11-22 18:16
UPD,See this is DEV....

**Comment by mrothauer** [comment] 2023-11-22 18:40
you can use develop, it is quite stable (and already in production usage)

the links to the files you need to translate are all here:
https://foodcoopshop.github.io/en/translation-guide.html

just change "develop" in the link to "russian-translation", and "en_US" to "ru_RU"
https://github.com/foodcoopshop/foodcoopshop/tree/develop/plugins/Network/resources/locales/en_US/network.po
will become
https://github.com/foodcoopshop/foodcoopshop/tree/russian-translation/plugins/Network/resources/locales/ru_RU/network.po

**Comment by mrothauer** [comment] 2023-11-22 18:42
If you know how to fork, you can return the changed files as a pull request, if not, just attach them in this issue.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by guland2000** [comment] 2023-11-22 22:39
Ok!

**Comment by mrothauer** [comment] 2023-12-06 20:55
@guland2000 do you need some help?

**Comment by guland2000** [comment] 2024-06-24 11:59
Please update this issue, with links, hope will have more time for translating now,
thank yo very much!

**Comment by guland2000** [comment] 2024-06-24 18:40
Links  above are still  not working.... For now, using local file from .zip for translating

**Comment by guland2000** [comment] 2024-06-24 20:51
Some question: what i need to translate in that case:

{0,plural,=1**{record}** other**{records}**}

only other?

**Comment by mrothauer** [comment] 2024-06-25 05:35
Hello again,

please use these files as your template (from the main branch, to use the latest stable version of the software):
https://github.com/foodcoopshop/foodcoopshop/tree/main/resources/locales/en_US/default.po
https://github.com/foodcoopshop/foodcoopshop/tree/main/plugins/Admin/resources/locales/en_US/admin.po
https://github.com/foodcoopshop/foodcoopshop/tree/main/plugins/Network/resources/locales/en_US/network.po

The workflow changed, you do not need to use poedit any more. Just open the files in any text-editor and translate the strings after msgstr.

After you have done that, depending on your git(hub) skills, either fork the project and create a pull request or just write a comment in this issue and attach the translated files.

> Some question: what i need to translate in that case:
> {0,plural,=1**{record}** other**{records}**}
> only other?

No, you need to translate the words "record" and "records"

**Comment by guland2000** [comment] 2024-06-25 18:57
Аnd translate? 
1) **InitDataSeed.php** 
2) Translate legal texts in template files [English files](https://github.com/foodcoopshop/foodcoopshop/tree/main/templates/element/**legal/**en_US)
3) https://github.com/foodcoopshop/foodcoopshop/blob/main/config/Locale/en_US/**date.php**

**Comment by mrothauer** [comment] 2024-06-25 19:18
> Аnd translate?
> 
> 1. **InitDataSeed.php**

Yes please

> 2. Translate legal texts in template files [English files](https://github.com/foodcoopshop/foodcoopshop/tree/main/templates/element/legal/en_US) (ok, here need adaptation not actually translation).

Correct. Look at the [German files](https://github.com/foodcoopshop/foodcoopshop/tree/main/templates/element/legal/de_DE), they are not empty.

> 3. https://github.com/foodcoopshop/foodcoopshop/blob/main/config/Locale/en_US/date.php

Yes, please. If date formats are different in russia

> 
> Thank you!

**Comment by guland2000** [comment] 2024-06-26 11:40
I have the feeling that in order to understand the connections (especially the subtleties of payment and deposit accounts), it will be necessary to deploy my own server and in the process to translate on a working (living server) ...

**Comment by guland2000** [comment] 2024-06-26 11:45
🤯

**Comment by guland2000** [comment] 2024-06-26 15:12
Just note if its an issue or not
When i set product as in bulk rythm of delivery then changed (trying) for rhytm drlivery a week (in admin as manufacturer) system cant give me access to edit product see the screen... if understood my explanation fo issue.
Thank you
![Uploading Снимок экрана_2024-06-26_17-01-43.png…]()

**Comment by guland2000** [comment] 2024-06-26 15:14
![Снимок экрана_2024-06-26_17-01-43](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/2275ac42-dd52-4569-bc26-d513ce3ddddc)

**Comment by mrothauer** [comment] 2024-06-26 16:58
I am currently working on a feature that is not yet finished but already deployed on demo-en and there was a bug.
I fixed it https://github.com/foodcoopshop/foodcoopshop/commit/b58513c85efe697f211a8145114a146a5515192b
Should be ok now.

**Comment by guland2000** [comment] 2024-06-26 20:51
What does a Credit and a Deposit mean in your case,
Credit needs to be set in the site settings (not to use for the participant at all and all the money is credited to him by a super admin?) but in that case why exist pay method in cart sum + Deposit sum...?

**Comment by mrothauer** [comment] 2024-06-26 21:10
> What does a Credit and a Deposit mean in your case

every user has a credit system, where the credit balance is shown (how much money is left to buy the products).

deposit is the amount of money that will be returned, if eg. an empty milk bottle is returned.

> Credit needs to be set in the site settings (not to use for the participant at all

no. in the settings there are only configurations for the credit handling. no credit is set in the settings.

> and all the money is credited to him by a super admin?)

did you read this link? https://foodcoopshop.github.io/guthaben/ - just translate it with deepl or google. you'll read, that there are two options to assign the money to the user: either via a csv-upload of the bank account transfers - or the user assigns it to himself and its later controlled by an admin. first option is recommended.

> but in that case why exist pay method in cart sum + Deposit sum...?

cart sum is sum of value of products, deposit sum is sum of value of deposit (eg. milk 1 euro + 0,50 cent for the bottle - which will be returned)

**Comment by guland2000** [comment] 2024-06-26 21:24
https://foodcoopshop.github.io/ yes all this (maybe during translation forgot something :-)
In my case (country) credit it something that you must return necessarily, because it was not your money, but borrowed from someone (bank, people, etc.) so i call this just Balance (Баланс) without any **Credit** !!!
That is why some times use just translator without thinking can be catastrophic and not professional :-)
Thank you!

**Comment by mrothauer** [comment] 2024-06-26 21:39
> In my case (country) credit it something that you must return necessarily, because it was not your money, but borrowed from someone (bank, people, etc.) so i call this just Balance (Баланс) without any **Credit** !!!

I am far from being a native speaker in English and so far no english native speaker has corrected my translation. maybe just "balance" is the correct term for that.

The German term for that is "Guthaben" and leo suggests "credit balance" as well as "balance"
https://dict.leo.org/englisch-deutsch/Guthaben

> That is why some times use just translator without thinking can be catastrophic and not professional :-) Thank you!

I totally agree with you.

**Comment by guland2000** [comment] 2024-06-26 23:38
1.In **Stock product (Stock)** 
 2.**Not in stock**
meaning ?
1.Product in somewhere in warehouse
2.Product is not in warehouse
3.Product available for now, today, next week, next months
4.Product in point of pickup
5.Ready for instant order, pickup day only today untill 00:00 hr  (I saw this line, but did not quite understand how it could affect (for two side)

**Comment by guland2000** [comment] 2024-06-26 23:56
Imprint ?
About company or something?

**Comment by guland2000** [comment] 2024-06-27 00:46
**Sum price excl.
Sum price incl.
Sum tax**
For TAX/VAT?
where i can see page with settings for this?

**Comment by guland2000** [comment] 2024-06-27 01:00
What do you mean? Situation for use in context?

**1. gross
2. Gross price
3. Total sum gross**

and

**1.net/piece
2.net
3.Price net
4.Total sum net**
(netto, without any charges such a deposit or something or what?)

**Surcharge** (how, from what?) how can i see this settings

**Base price?**  How to understand?

Thank you!

**Comment by mrothauer** [comment] 2024-06-27 06:07
> 1.In Stock product (Stock)
> 2.Not in stock
> meaning ?
> 1.Product in somewhere in warehouse
> 2.Product is not in warehouse

A product that is not explicitely declared as a "stock product", is a product that is pre-ordered every week (mostly fresh products like milk, yoghurt, vegetables, bread...) and then delivered to the coop where it is picked up by the members. a "stock product" (eg. noodles) is stored in the coop's pickup-room and not delivered every week.

> 3.Product available for now, today, next week, next months
> 4.Product in point of pickup
> 5.Ready for instant order, pickup day only today untill 00:00 hr (I saw this line, but did not quite understand how it could affect (for two side)

Sorry I did not understand the question.


> Imprint ?
> About company or something?

About the company and every manufacturer has its own imprint on his profile page.

> bulk order ? for order with long time to wait (something from another outside/country/region with long time delivery etc)?

Yes, for example. The pre-order period can be set individually (in contrast to pre-defined delivery rhythms on a weekly basis.

> Sum price excl.

Net price, price without tax / vat

> Sum price incl.

Gross price, price with tax / vat

> Sum tax

The sum of the tax / vat.

> For TAX/VAT?

it is the "value added tax", 

> where i can see page with settings for this?

It' is a bit hidden: Admin / Website administration / settings => top "Tax" https://demo-en.foodcoopshop.com/admin/taxes

> What do you mean? Situation for use in context?

> 1. gross
> 2. Gross price

it is the same

> 3. Total sum gross

somewhere the sum of all product's gross prices is shown

> 1.net/piece

Net price per piece

> 2.net
> 3.Price net

without tax (net + tax = gross)


> 4.Total sum net
(netto, without any charges such a deposit or something or what?)

net is always without tax.

> Surcharge (how, from what?) how can i see this settings

surcharge is only needed if you use the software in retail mode. in retail mode you have a purchase price and a selling price, the ration of both is the surcharge (eg. 30%)

> Base price? How to understand?

Products can have a "price per piece" (default setting) or a "price per weight" (eg. meat, 20 € / kg) the latter is the base price.


> WeekHeader/We. this is code, why to translate (Python calendar code)

It is just an abbreviation of the word "week" (German: Woche => Wo)

**Comment by guland2000** [comment] 2024-06-27 09:28
msgid "You_have_already_ordered_{0}_{1}_**times**_for_{2}."
msgstr "Du hast {0} bereits {1}**x** für den Abholtag {2} bestellt."
**X or times**
I can tell: one time, two time etc....  (can use word time) ?

**Comment by mrothauer** [comment] 2024-06-27 09:43
> msgid "You_have_already_ordered_{0}_{1}_**times**_for_{2}." msgstr "Du hast {0} bereits {1}**x** für den Abholtag {2} bestellt." **X or times** I can tell: one time, two time etc.... (can use word time) ?

yes, you can use whatever you want in your translation
but you cant change the word depending of the value of the variable {1}, therefore you need to chose either "time" or "times"
you would need to use pluralization, because its "one time", "two times" (with s). that is possible, but you would need to update the code.
so if "time" instead of "x" is fine for you, you can use that

> 2. **Instant order,** ready for pickup only today untill 00:00 hr (for example order this in one day (it does not matter at 11:00 or 18:00 hr) any way, product ready to pickup for today only!?

If you place an instant order, the pickup day is always set to the current day (regardless of the underlying delivery rhythm). it is used for making an order of stock products once the member picks up his pre-ordered products. the time does not matter.

**Comment by mrothauer** [comment] 2024-06-27 10:01
> In this context:
> msgid "Please_chose_if_it_is_a_payback_or_a_credit_upload."
> msgstr "Bitte wähle aus, ob es sich um eine Aufladung oder ein Rückzahlung handelt."
> Payback (Return the money back? As usual)

Yes. If a member ends his membership and there is still money on his (credit) balance, this is they way to equalize the balance to 0.

> Sorry if I ask too many questions

no problem, go for it!

**Comment by guland2000** [comment] 2024-06-27 10:24
> yes, you can use whatever you want in your translation
but you cant change the word depending of the value of the variable {1}, therefore you need to chose either "time" or "times"
you would need to use pluralization, because its "one time", "two times" (with s). that is possible, but you would need to update the code.
so if "time" instead of "x" is fine for you, you can use that

So i was in this shop only one **time** and after never was... that is? And i can use this word **time**?! 
Because in Russian language **X** does not exist in usual terminology for that. 
X does not affect the code, but only the meaning in the context?

**Comment by mrothauer** [comment] 2024-06-27 10:27
> So i was in this shop only one time and after never was... that is? And i can use this word time?!
> Because in Russian language X does not exist in usual terminology for that.
> X does not affect the code, but only the meaning in the context?

Yes, you can use the word "time". The x does NOT affect the code, you are right.

**Comment by guland2000** [comment] 2024-06-27 10:33
Just want to note that gross it is equal brutto (German translation as (brutto) more close then gross and for Russian language).
So i use brutto (брутто)

**Comment by guland2000** [comment] 2024-06-28 00:27
Sorry...again: **Stock**

**Stock** equal  Warehouse (kind of pickup room)? That is? 
**OR** 
example: this is to keep something for a future.... accumulated for any purpose, food reserves, fuel capacity etc...?
Not object (without any warehouse, garage etc) it is more verb stock something?

And you wrote: 
> "stock product" (eg. noodles) is stored in the coop's pickup-room and **not delivered every week**.
but i see the stings: 
msgid "The_**delivery_rhythm_of_stock_products_is_always_weekly**."
msgstr "Der Lieferrhythmus von Lagerprodukten ist immer \"wöchentlich\" und kann nicht geändert werden."
?

**Comment by mrothauer** [comment] 2024-06-28 06:13
> Stock equal Warehouse (kind of pickup room)? That is?

I don't think that I used Stock in sense of Warehouse (but I am not 100% sure)

It most likely is used for the amount of goods that are "on stock" => like "stock level"

**Comment by guland2000** [comment] 2024-06-28 06:27
An example: 
I have a food for one week! (**that mean i made stock of food**). After one week  i need buy again food, so i made stock of food, like this?

**Comment by mrothauer** [comment] 2024-06-28 06:43
The availability has nothing to do if a product is a stock product or it is a product that can be pre-ordered. Both of them can be available or not.
Just skip the translation for now, I am sure that you'll get the context right once you work with the software.

**Comment by guland2000** [comment] 2024-06-28 07:45
Last chance, **Stock** is:
The product is not ready yet, it is being prepared, still in progress, will be ready soon.
I can order it but must to wait!!!
Yes?! That is????????

**Comment by mrothauer** [comment] 2024-06-28 08:28
Yes. If a product is not "on stock", then it cannot be ordered. But not because "it is prepeared", but theres nothing left, sold out.

**Comment by guland2000** [comment] 2024-07-01 10:00
Please check default.po (Russian) note that i have some additional number of strings because newline character...

**Comment by guland2000** [comment] 2024-07-01 10:36
and network.po (Rus)

**Comment by mrothauer** [comment] 2024-07-01 11:53
Target branch of pull request should be issue-975-russian-translation and not develop

**Comment by guland2000** [comment] 2024-07-01 12:09
> Target branch of pull request should be issue-975-russian-translation and not develop

ok, change it for network.po....
Need to change all translation or you made it yourself?

**Comment by mrothauer** [comment] 2024-07-01 12:12
default.po is in the branch, network.po and admin.po needs to be done by you (via pr)
https://github.com/foodcoopshop/foodcoopshop/compare/develop...issue-975-russian-translation

**Comment by guland2000** [comment] 2024-07-01 12:15
> default.po is in the branch, network.po and admin.po needs to be done by you (via pr) [develop...issue-975-russian-translation](https://github.com/foodcoopshop/foodcoopshop/compare/develop...issue-975-russian-translation)
Ok, will note whis for future...

**Comment by mrothauer** [comment] 2024-07-01 13:53
I set up a new domain for you: https://demo-ru.foodcoopshop.com/

I reset all translations of routes (msgid starts with "route_") to the english ones (non-cyrillic). forms (eg. login form) would not work with special characters in url.

maybe there is a latin "translation" of the cyrillic alfabet, then you could adapt the english translations.

**Comment by guland2000** [comment] 2024-07-01 18:37
Are you talking about transcription? **Babushka, matryoshka, balalaika.... vodka?!**

**Comment by mrothauer** [comment] 2024-07-01 18:54
yes I think thats it. please transcribe all messages prefixed with "route_"

**Comment by guland2000** [comment] 2024-07-02 09:50
I'm updated route_ on https://github.com/foodcoopshop/foodcoopshop/blob/issue-975-russian-translation/resources/locales/ru_RU/default.po but did not see any changes (made something wrong, not in this file?)

**Comment by mrothauer** [comment] 2024-07-02 10:36
you need to create a pull request to this branch of the main repo: https://github.com/foodcoopshop/foodcoopshop/compare/develop...issue-975-russian-translation
then i need to merge and deploy it manually
then you see your changings on demo-ru.foodcoopshop.com

**Comment by guland2000** [comment] 2024-07-02 10:54
Can you link it were...
And **date.php** was changed?
Sorry for that.

**Comment by guland2000** [comment] 2024-07-02 11:44
For testing: now i am pull network.po... so it is mean you will do it manually  (just need to wait)?

**Comment by mrothauer** [comment] 2024-07-02 15:20
I merged an deployed your changings

**Comment by guland2000** [comment] 2024-07-02 17:04
Pull request was created for **date.php**.... 
![Снимок экрана_2024-07-02_18-56-47](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/6fe38247-33eb-4d8d-a6ed-efc3c7e25833)
and
![Снимок экрана_2024-07-02_19-03-31](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/bd412191-38d3-4413-8481-3ac223457d0a)

**Comment by guland2000** [comment] 2024-07-02 21:37
admin.po pull request...

**Comment by guland2000** [comment] 2024-07-02 23:09
resources/locales/en_US/**cake.po**
Translate it ? See de_DE only partially translated...

**Comment by mrothauer** [comment] 2024-07-03 06:10
> resources/locales/en_US/**cake.po** Translate it ? See de_DE only partially translated...

yes please, it is enough to translate the parts that are translated in de_DE

**Comment by mrothauer** [comment] 2024-07-03 06:16
i just deployed the latest pr

**Comment by guland2000** [comment] 2024-07-03 07:06
Some strings a not translated in web (but from me it was)
For exmpl: Was: **List of allergens**: string 1187 - Must be: **Список аллергенов**
![Снимок экрана_2024-07-03_08-50-48](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/bcf0c89d-d908-4b83-af2a-1a602aefd724)

Member card generate: ?????? ?????
![Снимок экрана_2024-07-03_08-31-34](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/5db0ac1e-da84-425f-9b65-96ff5026c0c5)

Some menu still in English in: change password, My data
![Снимок экрана_2024-07-03_09-01-46](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/2c506e33-dcf4-4c80-91a3-a211a92543f5)
 Right menu: Delivery time, etc
![Снимок экрана_2024-07-03_09-03-53](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/893f6732-b1bd-4d7b-ae4b-7268a6870387)

Reason maybe AND in initdataseed.php (still in progress.... by me)

**Comment by guland2000** [comment] 2024-07-03 10:03
![Снимок экрана_2024-07-03_12-01-59](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/f9eda1a0-b9de-4615-9e9d-5a2a56cf368a)
Still in German

**Comment by mrothauer** [comment] 2024-07-03 10:22
> Still in German

You need to wait a bit. First your PR need to be merged (done 1 min ago), then I manually need to deploy it (done now). 

??? in PDFs: I need to change the font than it will work. As I have a lot of other things to do, that will last some days.

**Comment by guland2000** [comment] 2024-07-03 10:29
> > Still in German
> 
> You need to wait a bit. First your PR need to be merged (done 1 min ago), then I manually need to deploy it (done now).
> 
> ??? in PDFs: I need to change the font than it will work. As I have a lot of other things to do, that will last some days.

Ok, no problem! About fonts, Russians looks very ugly (not well looking). Just for note :-)

**Comment by mrothauer** [comment] 2024-07-03 10:44
> Ok, no problem! About fonts, Russians looks very ugly (not well looking). Just for note :-)

Font is updated! Looks great now!

**Comment by guland2000** [comment] 2024-07-03 10:51
> > Ok, no problem! About fonts, Russians looks very ugly (not well looking). Just for note :-)
> 
> Font is updated! Looks great now!

Thank you, looking good! Better then was.

**Comment by mrothauer** [comment] 2024-07-03 10:52
FYI: A lot of strings (like eg the Right Box with "Delivery time" in it's header) are located in this file (and not in the po-files):
https://github.com/foodcoopshop/foodcoopshop/blob/develop/config/Seeds/locale/ru_RU/InitDataSeed.php

As soon as it is translated completely, I'll deploy it

**Comment by mrothauer** [comment] 2024-07-03 11:16
PDFs are working!
![image](https://github.com/foodcoopshop/foodcoopshop/assets/527787/2e38cc6b-4ecb-4455-ae8c-9b64e5e29c1d)

**Comment by guland2000** [comment] 2024-07-03 13:21
Pull some corrections in default and admin.po, before i saw my changes, now see that everything goes back, like i did not made corrections.
Is it OK it is temporary all just technical issues?

**Comment by mrothauer** [comment] 2024-07-03 18:33
> Pull some corrections in default and admin.po, before i saw my changes, now see that everything goes back, like i did not made corrections. Is it OK it is temporary all just technical issues?

Normally no changing should be lost. Maybe you edited a file that was not up to date? It should not happen again. And if so, just look up the merged pull requests and copy your changes.

**Comment by mrothauer** [comment] 2024-07-03 18:34
I just deployed the last 4 PRs

**Comment by guland2000** [comment] 2024-07-03 19:01
Going to be confused....
How to explain for myself this: especially **Bulk oder** (sure it is day for choosing without rhythm of delivery! But every time when i am choosing  **Send order list day** still (or now) can not translate without errors...
I need explanation, what is this, so Ok:
**.Delivery rhythm** 
1. (each day in the week, with some steps every 2nd week etc.... ok
2. bulk order (means in any day of week, month can be after 2 month????
3. Order possible (means can set data when costumers can make order till some date, after no, accept order is closed)
4. Send order list day (what is this? Send e.mail, send notifications to costumers? Order list... but each time when i set up date always warning like this: 
![Снимок экрана_2024-07-03_20-02-06](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/68409a48-375c-4584-a685-6a7a7092414f)
5.Delivery day (day when i can pickup my зкщвгсеs? But under this field i see note: The product **с_an be ordered from now on_** and after i see below: _You can change the delivery rhythm for multiple products by selecting them and then clicking the "Actions" button._
And string telling me another, the are different  (En one thing De other.....)
????? Maybe some scheme or visual pictures
And i wrote all info in  https://foodcoopshop.github.io/bestellabwicklung/ any way cant help me...

**Comment by guland2000** [comment] 2024-07-03 19:05
Upps see the date of year, sorry, will try again...

**Comment by guland2000** [comment] 2024-07-03 19:52
> > Pull some corrections in default and admin.po, before i saw my changes, now see that everything goes back, like i did not made corrections. Is it OK it is temporary all just technical issues?
> 
> Normally no changing should be lost. Maybe you edited a file that was not up to date? It should not happen again. And if so, just look up the merged pull requests and copy your changes.

So for example: default.po_Ru
2350 Stay signed in
2351 now you can see, it is correct: **запомнить**, (before it was wrong **Оставайтесь в системе**)
Lets see actual web page ! Same last wrong **Оставайтесь в системе** market it in green....
![Снимок экрана_2024-07-03_21-51-41](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/edc97c72-fca5-4607-94cd-1fb67b93a514)

**Comment by guland2000** [comment] 2024-07-03 23:07
I see maybe it is an error (issue)
In menu of Member order details we can choose Group by member (for what?)

![Снимок экрана_2024-07-04_00-55-13](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/252e7ef2-11c6-4995-b2f3-db6b57f90588)

but menu Manufacture order detail we can choose only Group by product!
Must be vice-versa.... 
The member does not need to know about the orders of others, but on the contrary, the manufacturer should have more information about who, what and when purchased the product from him.

![Снимок экрана_2024-07-04_00-56-43](https://github.com/foodcoopshop/foodcoopshop/assets/10272327/1ac61809-09e3-4df8-a5a1-1afaa49a16aa)

**Comment by mrothauer** [comment] 2024-07-04 06:40
just deployed the latest prs

* Group By Issue: That's intended behavior, the grouped-by-member-view contains elements that are not relevant for manufactueres, that's why manufacturers do not get this option

**Comment by guland2000** [comment] 2024-07-04 10:09
About this one in rhythm of delivery: **Send order list day**
What is this? Send e.mail, send notifications to costumers? Order list?
Do I understand correctly?

**Comment by mrothauer** [comment] 2024-07-04 10:17
It is the day when the order lists are sent. normally on a weekly basis, for bulk orders its a date.

**Comment by guland2000** [comment] 2024-07-04 10:23
> It is the day when the order lists are sent. normally on a weekly basis, for bulk orders its a date.

and why i can not have order lists when making **bulk orde**r (in **same day**) only in the next day?

**Comment by mrothauer** [comment] 2024-07-04 10:30
because by default the whole day must be over (midnight), theoretically there can be a last order on 23:59 h, before the script runs and sends all order lists
thats why the same day cannot be selected. you would also have to specify the time (and that is not possible)

**Comment by guland2000** [comment] 2024-07-08 12:07
If its Ok differences in code for En and German?
(590,1,'FCS_CUSTOMER_CAN_SELECT_PICKUP_DAY','Mitglied kann Abholtag beim Bestellen selbst auswählen.','0','readonly',590,'de_DE','2020-07-06 10:34:35','2020-07-06 10:34:35'),
and
591,1,'FCS_SEND_INVOICES_TO_CUSTOMERS','Retail mode activated?.','0','readonly',580,'en_US','2020-10-29 10:06:39','2020-10-29 10:06:39'),

**Comment by guland2000** [comment] 2024-07-08 12:52
Hello Mario!
Most things are done (can propose that if somebody wants to make The terms of use, policy, etc. should already translate on their own based on the peculiarities, that they want to see themselves on the site... Isn't it?

**Comment by mrothauer** [comment] 2024-07-08 13:39
> Most things are done

Great! But there is one translation missing because I merged a new feature
https://github.com/foodcoopshop/foodcoopshop/commit/54b76d33f42e01f9dcac4f95c480f139e4db0e4b

> (can propose that if somebody wants to make The terms of use, policy, etc. should already translate on their own based on the peculiarities, that they want to see themselves on the site... Isn't it?

You are right. Thats not really a translation but an adaption of the legal texts for the corresponding country.

The Ruble-Sign looks good, even without your font.

As soon as you tell me that the translation is finished, I'll merge your changings into the develop branch and prepare a release for you. With that, you can run your own server.

If you can't (or do not want to) do that work, I can offer you to host the software on my server. Thats how I earn money with this open source project. But feel free to download and host it by yourself!

**Comment by guland2000** [comment] 2024-07-08 13:47
Thank you! Many thanks!
But still need some corrections (with you new sting above and something to polish to make perfect as it possible)
Can not find this string to change in (it is imprint i think) 
![Uploading 1000002066.jpg…]()

**Comment by mrothauer** [comment] 2024-07-08 13:49
i cant open the image

**Comment by mrothauer** [comment] 2024-07-08 14:36
Thats content
https://demo-ru.foodcoopshop.com/admin/pages
![image](https://github.com/foodcoopshop/foodcoopshop/assets/527787/0a629a9d-1d9d-40b6-9b41-fcb4f1c53d81)

use the pen-icon to the left to edit the string

but this is for this demo-installation only as the content changes for your installation

**Comment by guland2000** [comment] 2024-07-11 09:41
Hello, Mario
You have (I don't know the time, the ability to help) to deploy a server on my VPS, I didn't understand everything about the installation (I have experience with deployment but with other specifics). I will provide everything necessary for this. And in general, it would be cool if the creator did it. If not, then I will understand, no problem. Just a request. Thank you

**Comment by mrothauer** [comment] 2024-07-11 09:53
Hi Andrei,

sorry, but I only offer paid hosting on my server.

If you want to have an offer for the installation fee (once) and the service fee (yearly), please drop me an email (office@foodcoopshop.com)

If you want to install by yourself and have questions concerning the installation, I can give you support.

**Comment by guland2000** [comment] 2024-07-11 10:06
_As soon as you tell me that the translation is finished, I'll merge your changings into the develop branch and prepare a release for you. With that, you can run your own server._

I understand, thank you (you wrote a post above about the release that you prepared with Russian) Please give me a link (I'm not sure if I understood correctly what time to put the developer or stable version).

**Closed** 2024-07-11 10:09 UTC

**Comment by guland2000** [comment] 2024-07-11 10:14
....so need to use develop 4.1 ?

**Comment by mrothauer** [comment] 2024-07-11 10:17
Sure, you can download your release [here](
https://www.foodcoopshop.com/wp-content/uploads/releases/FoodCoopShop-develop-russian-translation.zip).
Its the current develop branch with the pre-installed vendors.
Good luck with the installation and thank you for the translation!

**Comment by guland2000** [comment] 2024-07-11 10:22
....and last one, deploy in docker or docker only for tests (not production)?

**Comment by mrothauer** [comment] 2024-07-11 10:41
the provided docker config is meant to be used for development environment only
but if you know what you do, you can take it as a kind of template and use / adapt it for production

**Comment by guland2000** [comment] 2024-07-11 10:48
see it, language is not in main branch (only in develop) you will implement it only in future 2025

**Comment by mrothauer** [comment] 2024-07-11 10:56
That's what I intended, your are right.
But as there were some extra changings besides your translation, mainly changing fonts, I decided to use the develop branch as the target branch of your changings. this branch is pretty stable thanx to more than 600 automated tests.

**Comment by mrothauer** [comment] 2024-07-11 11:14
Yes, I can do that but it will take some days. I suggest that you try with the version I provided.

**Comment by guland2000** [comment] 2024-07-11 11:15
> Yes, I can do that but it will take some days. I suggest that you try with the version I provided.

Will wait, thank you!

**Comment by mrothauer** [comment] 2024-07-11 19:27
here you go: https://www.foodcoopshop.com/wp-content/uploads/releases/FoodCoopShop-main-russian.zip

**Comment by mrothauer** [comment] 2024-07-11 19:28
FYI: demo-ru.foodcoopshop.com will still be available and based on develop (not main)

**Comment by mrothauer** [comment] 2024-11-27 06:41
Hi @guland2000 how is it going?
It would be great for the FoodCoopShop project, if I can add your initiative to my map (visible eg. on https://www.foodcoopshop.com/)
Could you tell me the domain where it's running?
Thank you,
Mario
